name: 'Open every website from sitemap'
description: 'Open every website from sitemap to populate cache'
author: "Jakub Pomykała"
branding:
  icon: 'globe'
  color: 'blue'
inputs:
  sitemap-url:
    description: 'URL to the sitemap file'
    required: true
    default: ''
runs:
  using: 'composite'
  steps:
    - name: "Setup Java"
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: "Download artifact"
      uses: actions/download-artifact@v4
      with:
        name: cache-populate.jar
    - name: "Run JAR"
      run: "java -jar cache-populate.jar fetch --sitemap ${{ inputs.sitemap-url }}"
      shell: bash
