name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Open every website from sitemap
        uses: jpomykala/sitemap-fetch-pages-action@main
        with:
          sitemap-url: 'https://renderform.io/sitemap.xml'
