name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B clean install -DskipTests --file pom.xml
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: cache-populate
          path: target/cache-populate.jar
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          make_latest: true
          tag_name: latest
          files: target/cache-populate.jar
      - name: Open every website from sitemap
        uses: jpomykala/sitemap-fetch-pages-action@main
        with:
          sitemap-url: 'https://renderform.io/sitemap.xml'
